version: '3.8'

services:
  sylvera-app:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - NODE_ENV=development
    ports:
      - '3000:3000'
    volumes:
      - .:/usr/src/app
    command: ['npm', 'start']
