# Generated by Django 4.1.4 on 2022-12-07 16:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Meter',
            fields=[
                ('mpan', models.BigIntegerField(primary_key=True, serialize=False)),
                ('serial_number', models.CharField(default='', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Reading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.DateTimeField(verbose_name='Reading timestamp')),
                ('value', models.FloatField(default=0.0)),
                ('source', models.CharField(default='', max_length=255)),
                ('meter', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='readings.meter')),
            ],
        ),
    ]
